###
POST http://127.0.0.1:3000/api/v1/snippet HTTP/1.1
Content-Type: application/json

{
    "author": "jose",
    "source": "https://github.com/jadsonlucio/code_snippets/printcplus",
    "language": "C++",
    "code_snippet": "std:cout << 'teste';",
    "description": "print on c++",
    "algorithm": "none",
    "library": "std",
    "category": "learning",
    "difficulty": 1,
    "language_version": "0.1.0",
    "library_version": "0.1.0",
    "dependencies": "numpy==0.10, pandas==0.1.1"
}

###
GET http://127.0.0.1:3000/api/v1/snippet/1 HTTP/1.1

###
PATCH http://127.0.0.1:3000/api/v1/snippet/1
Content-Type: application/json

{
    "author": "jadson lucio",
    "source": "http://github/test/code.py"
}

###
DELETE  http://127.0.0.1:3000/api/v1/snippet/3

